version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - xvfb
    - snapd
  commands:
    - snap install drawio

sphinx:
  configuration: doc/source/conf.py

python:
   install:
   - requirements: doc/source/requirements.txt
