[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
# Note: To flash the rp2040 make sure it is in BOOTSEL mode and then:
# CARGO_TARGET_THUMBV6M_NONE_EABI_RUNNER="elf2uf2-rs -d" cargo run
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "no-vectorize-loops",
  "-C", "link-arg=-Tembedded-test.x"
]

[target.x86_64-unknown-linux-gnu]
runner = "embedded-test-std-runner"
rustflags = [
  "-C", "link-arg=-Tembedded-test.x"
]

[build]
target = "thumbv6m-none-eabi"

[env]
# Prevent showing warning that can be ignored: "Failed to switch to DP Multidrop ...".
# See e.g. https://github.com/probe-rs/probe-rs/issues/3316
RUST_LOG = "probe_rs::architecture::arm::communication_interface=error"
