services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    volumes:
      - ..:/home/${USER}/project
      - /media/${USER}:/media/${USER}
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /home/${USER}/project/software
    stdin_open: true
    tty: true
    privileged: true
    stop_grace_period: 0s
