services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    volumes:
      - .:/home/${USER}/software
      - ../project_management:/home/${USER}/project_management
      - /media/${USER}:/media/${USER}
    working_dir: /home/${USER}/software
    stdin_open: true
    tty: true
    privileged: true
    stop_grace_period: 0s
