[package]
name = "firmware"
version = "0.0.0" # Versioning is done automatically. This is just a placeholder.
edition = "2024"

[dependencies]
lib = { version = "=0.0.0", path = "../../lib" }
embassy-rp = { version = "=0.10.0", features = ["defmt", "rp2040", "critical-section-impl"] }
embassy-executor = { version = "=0.10.0", features = ["executor-thread"], optional = true }
embassy-sync = { version = "=0.8.0", features = ["defmt"] }
embassy-usb = { version = "=0.6.0", optional = true }

# embassy-time = { version = "=0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-time = { version = "=0.5.1", features = ["defmt"] } # TODO: welche feature sind notwendig?

cortex-m-rt = "=0.7.5"
static_cell = "=2.1.1"
portable-atomic = { version = "=1.13.1", features = ["critical-section"] }

defmt = "=1.1.1"
defmt-rtt = "=1.3.0"
panic-probe = { version = "=1.0.0", features = ["print-defmt"] }
fixed = "1.31.0"

# see: https://docs.rs/embedded-test-linker-script/0.1.0/embedded_test_linker_script/
embedded-test-linker-script = { version = "=0.1.0", optional = true }
embedded-test = { version = "=0.7.1", default-features = false, features = ["embassy-010"], optional = true }
embedded-storage-file = { version = "=0.2.0", optional = true }
embedded-storage-async = {version = "=0.4.1", optional = true}

embassy-net = { version = "=0.9.1", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "proto-ipv4"] }
rust-mqtt = { version = "=0.5.1", default-features = false, features = ["defmt", "v5", "bump"] }

cyw43 = { version = "=0.7.0", features = ["defmt"] } # note: defmt may be disabled because: https://github.com/embassy-rs/embassy/issues/3694
cyw43-pio = { version = "=0.10.0", features = ["defmt"] }

const-str = "=1.1.0"

[lib]
harness = false

[[bin]]
name = "firmware"
path = "src/main.rs"
test = false

[features]
default = [
    "embassy-executor/platform-cortex-m",
    "embassy-executor/defmt",
    "embassy-usb",
    "embedded-test-linker-script",
]
host-test = [
    "embassy-executor/platform-std",
    "embedded-test/std",
    "embedded-storage-file",
    "embedded-storage-async"
]
target-test = [
    "embassy-executor/platform-cortex-m",
    "embassy-executor/defmt",
    "embassy-usb",
    "embedded-test/default",
]
