services:
    main:
        build:
            dockerfile: Dockerfile
        volumes:
            - ..:/vscode/project
        stdin_open: true
        tty: true
        privileged: true
        stop_grace_period: 0s
