services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/${USER}/features
      - ../project_management:/home/${USER}/project_management
    working_dir: /home/${USER}/features
    stdin_open: true
    tty: true
    privileged: true
    stop_grace_period: 0s
