services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/project
    working_dir: /usr/project
    stdin_open: true
    tty: true
    privileged: true
    stop_grace_period: 0s
