[package]
name = "firmware"
version = "0.0.0" # Versioning is done automatically. This is just a placeholder.
edition = "2021"

[dependencies]
embassy-sync = { version = "=0.8.0", features = ["defmt"] }
embassy-executor = { version = "=0.10.0", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"], optional = true }
embassy-rp = { version = "=0.10.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp2040"] }
embassy-usb = { version = "=0.6.0", features = ["defmt"] }
embassy-futures = { version = "=0.1.2" }
embassy-time = { version = "=0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
# embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
defmt = "=1.1.0"
defmt-rtt = "=1.2.0"
fixed = "=1.31.0"
cortex-m-rt = "=0.7.5"
panic-probe = { version = "=1.0.0", features = ["print-defmt"] }
static_cell = "=2.1.1"
portable-atomic = { version = "=1.13.1", features = ["critical-section"] }
cyw43 = { version = "=0.7.0", features = ["defmt"] } # note: defmt was disabled because: https://github.com/embassy-rs/embassy/issues/3694
cyw43-pio = { version = "=0.10.0", features = ["defmt"] }
embassy-net = { version = "=0.9.1", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "proto-ipv4"] }
rand_core = "=0.10.1" # this needs to be an older version because of embassy-rp 0.4.0
embedded-nal-async = "=0.9.0"
embedded-time = "=0.12.1"
rust-mqtt = { version = "=0.5.1", default-features = false, features = ["v5", "bump", "defmt"] }
cfg-if = "=1.0.4"
heapless = "=0.9.3"

[dev-dependencies]
tokio = { version = "=1.52.3", features = ["macros", "rt-multi-thread"] }
mockall = "=0.14.0"

[build-dependencies]
chrono = "0.4.45"

[features]
default = ["embassy-executor"]
test = []

[profile.dev]
debug = 2
opt-level = 0
overflow-checks = true
