on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4

        -   name: build software
            uses: devcontainers/ci@v0.3
            with:
                configFile: .devcontainer/devcontainer.json
                runCmd: ./run.py --verbose --pseudo_tty_off software --build

        -   name: check for file changes
            run: |
                if [ -n "$(git status --porcelain)" ]; then
                    echo "The build changed files in the repository. Please check the changes:"
                    git status --porcelain
                    exit 1
                fi
