on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   uses: actions/checkout@v4

        -   run: ./run.py --software --build --verbose --pseudo_tty_off

        -   name: check for file changes
            run: |
                if [ -n "$(git status --porcelain)" ]; then
                    echo "The build changed files in the repository. Please check the changes:"
                    git status --porcelain
                    exit 1
                fi
