on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   name: Checkout
            uses: actions/checkout@v4

        -   name: build documentation
            run: ./doc/run.py --build --verbose --pseudo_tty_off

        -   name: Setup Pages
            uses: actions/configure-pages@v5

        -   name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: documentation
                path: 'doc/build/html'
