on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   name: checkout
            uses: actions/checkout@v4

        -   name: create documentation
            # first run the software tests to create the reports for the documentation
            run: |
                ./run.py --software --test --verbose --pseudo_tty_off
                ./run.py --doc --build --verbose --pseudo_tty_off

        -   name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: documentation
                path: 'doc/build/html'
