on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   name: checkout
            uses: actions/checkout@v4

        -   name: create documentation
            run: ./doc/run.py --build --verbose --pseudo_tty_off

        -   name: upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: 'doc/build/html'
