on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   name: checkout
            uses: actions/checkout@v4

        -   name: create documentation
            run: ./doc/run.py --build --verbose --pseudo_tty_off

        -   name: setup pages
            uses: actions/configure-pages@v5

        -   name: upload pages artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: 'doc/build/html'

        -   name: deploy to GitHub pages
            uses: actions/deploy-pages@v4
