on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v4

        -   name: create documentation
            uses: devcontainers/ci@v0.3
            with:
                configFile: .devcontainer/devcontainer.json
                runCmd: |
                    ./run.py --verbose --pseudo_tty_off software --test
                    ./run.py --verbose --pseudo_tty_off doc --build

        -   name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: documentation
                path: 'doc/build/html'
