on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   uses: actions/checkout@v4

        -   name: allow container write access to repository
            run: sudo chmod -R a+rwX .

        -   run: ./run.py --verbose --pseudo_tty_off software --test

        -   name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: unit-test-report
                path: software/firmware/build/unit-test-report.txt
