on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v6

        -   name: run unit tests
            uses: devcontainers/ci@v0.3
            with:
                configFile: .devcontainer/devcontainer.json
                push: never
                runCmd: ./run.py --verbose --pseudo_tty_off software --host_test

        -   name: upload artifact
            uses: actions/upload-artifact@v7
            with:
                name: host-test-report
                path: software/targets/rp2040/target/host-test-report.txt
