on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: setup
            run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

        -   uses: actions/checkout@v4

        -   run: ./run.py --software --test --verbose --pseudo_tty_off | tee unit-test-report.txt

        -   name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: unit-test-report
                path: unit-test-report.txt
